version: "3.8"
services:
  wiremocked:
    image: rodolpheche/wiremock
    ports:
      - 80:80
    volumes:
      - C:\Projects\mock-testing-example\wiremock:/home/wiremock
    command: --port 80

  webapp:
    build:
      context: webapp
    ports:
      - 5000:5050
    volumes:
      - C:\Projects\mock-testing-example\webapp:/usr/src/app
    links:
      - wiremocked:ip.jsontest.com
      - wiremocked:api.weatherstack.com
    depends_on:
      - wiremocked
